name: Deno

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deno:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4.1.2

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.4
        with:
          deno-version: vx.x.x

      - run: |
          cd types/schemas
          curl -o openai.yaml https://raw.githubusercontent.com/openai/openai-openapi/master/openapi.yaml

      - name: Run openapi
        run: |
          cd types/schemas
          deno run -A npm:openapi-zod-client "openai.yaml" -o "openai.ts"
          sed -i '1,2s|@zodios/core|../../deps.ts|g;1,2s|zod|../../deps.ts|g' openai.ts
          rm openai.yaml

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno task test

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.0.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
