name: Deno

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4.1.1

      - name: Setup Deno
        uses: denoland/setup-deno@v1.1.4
        with:
          deno-version: vx.x.x

      - run: |
          cd types
          curl -o openai.yaml https://raw.githubusercontent.com/openai/openai-openapi/master/openapi.yaml
          curl -o litellm.json https://raw.githubusercontent.com/BerriAI/litellm/main/litellm/proxy/openapi.json
          curl -o cloudflare.yaml https://raw.githubusercontent.com/cloudflare/api-schemas/main/openapi.yaml
          pip install icecream
          python ../.github/workflows/split-openapi.py
          mv cloudflare-filtered.yaml cloudflare.yaml

      - name: Run openapi
        run: |
          cd types
          deno run -A npm:openapi-zod-client "openai.yaml" -o "openai.ts"
          deno run -A npm:openapi-zod-client "litellm.json" -o "litellm.ts"
          deno run -A npm:openapi-zod-client "cloudflare.json" -o "cloudflare.ts"
          sed -i '1,2s|@zodios/core|../deps.ts|g;1,2s|zod|../deps.ts|g' openai.ts
          sed -i '1,2s|@zodios/core|../deps.ts|g;1,2s|zod|../deps.ts|g' litellm.ts
          sed -i '1,2s|@zodios/core|../deps.ts|g;1,2s|zod|../deps.ts|g' cloudflare.ts
          rm openai.yaml
          rm litellm.json
          rm cloudflare.json

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Run tests
        run: deno test -A

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
